### PR TITLE
fix: kill now unused senderid_list cruft

### LINKED ISSUE #544: Cleanup senderid_list remnants
Most of the internal senderid_list usage (besides parsing it into senderIDs) is cruft leftover from probably from the old senderids.py module, among other things.

### PR DESCRIPTION
**Pull request by pjenvey**
closes #544

### CODE REVIEW

**Comment by pjenvey** [comment]
@jrconlin r?

**Comment by jrconlin** [comment]
r+

**Comment by bbangert** [comment]
The missing test coverage is for the new try/except.

**Comment by bbangert** [comment]
r+, checks all done

**Pull request merged**
