### PR TITLE
feat: Add FCM router support

### LINKED ISSUE #517: Add FCM router support
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1286912, there are a few changes that need to be done to move from GCM to FCM, one of which is to change the endpoint the server calls from 
http.googleapis.com/gcm/ to fcm.googleapis.com/fcm/

We'll want to create a new router type of "fcm", that points to the new endpoint URL. This new router can mostly be a clone of the GCM one.

### PR DESCRIPTION
**Pull request by jrconlin**
Adds 'fcm' as a client selectable router, to allow 'gcm' to persist or
act as a fallback.

closes #517 

@bbangert r?

### CODE REVIEW

**Comment by bbangert** [comment]
Moar reviewers...

**Comment by pjenvey** [comment]
There's just so little difference between this & GCM's router (just the constructor) I'd suggest consolidating them a bit somehow. Might they diverge much in the future?

**Comment by jrconlin** [comment]
Yeah, I thought about combining them, except we hit problems with doing something like that in the past. The way I look at it is that the "GCM" router would be locked while any future changes would hit the "FCM" router. This would also mean that older clients (which may or may not update to use FCM) could continue for a while. Plus, as I note in a few locations, there's a LOT more work the client has to do to use FCM. This, at least, lets clients determine when they want to switch over without adding undue complexity to our code.  

Fortunately, these routers pretty much just hand off data. Still, I definitely understand the sentiment.

**Comment by bbangert** [comment]
r+, not a fan of the duplication, but in theory we lose the GCM at some point and FCM can improve independently (or hopefully we just use SNS).

**Pull request merged**
