### PR TITLE
feat: Code cleanup

### PR DESCRIPTION
**Pull request by jrconlin**
* replaces python reserved word var names
* replaces mixed case var names
* fixes setting chain breaks (message_read/write_throughput)
* removes unneeded var instantiations
* normalize HealthHandler to base from AutoendpointHandler, so
ap_settings is known
* instantiate from dict() rather than {}
* limit except handlers to known exceptions

issue #612

### CODE REVIEW

**Comment by pjenvey** [comment]
HealthHandler doesn't need to subclass AutoendpointHandler, the initialize method's from cyclone RequestHandler, so HealthHandler(.., ap_settings=ap_settings) in the test should just work as is (that makes a bit more sense too because it's not just for the endpoint).

Also the cyclone add_handlers calls in main should accept the same style as Application() -- so we cleanup the .ap_settings class vars dance in main.py by doing add_handlers([(.., HealthHandler, dict(ap_settings=ap_settings)) like we do here:

https://github.com/mozilla-services/autopush/blob/54c4526/autopush/main.py#L540

**Comment by jrconlin** [comment]
Yeah, this is going to be bikeshedding on an unbelievable scale.

Most of these changes were driven by wanting to make PyCharm shut up. In the case of HealthHandler, it's due to the fact that PyCharm can't work out the source for `ap_settings`, unless you specify the direct class chain. In some respects, I understand since cyclone does a fair bit of magic to get that to happen that's not very obvious.

Happy to revert it if that's a problem. If so, I'll probably add a comment to the docstring explaining what's going on.

**Comment by pjenvey** [comment]
ah ok, no worries. let's get it in before more conflicts pop up

r+

**Comment by bbangert** [comment]
This appears to include other commits that are already on master, are we going to get more dupe commits in the history if this is merged as-is?

**Comment by bbangert** [comment]
r+

**Pull request merged**
