### PR TITLE
Add table naming and provisioning throughput options.

### LINKED ISSUE #4: Make storage/router DynamoDB table names configurable
The router/storage table names used must be configurable, as 'router' and 'storage' could cause name conflicts.

### PR DESCRIPTION
**Pull request by bbangert**
Closes #4.

### CODE REVIEW

**Comment by jrconlin** [comment]
r+ (mostly)

I'm ok with using the env/CLI approach to app configuration, but it makes for some pretty unwieldy starts. I don't think we'll hit 262K command line length any time soon, and it's certainly possibly to offload to the environment. I worry that there might be a risk of op error. We may want to check with Ops to see if there's a more preferred means of specifying configuration.

**Comment by kitcambridge** [comment]
`configargparse` can read from a config file too, right?

**Comment by bbangert** [comment]
That's correct, we could add a config file option, and configargparse can use that as well.

**Comment by jrconlin** [comment]
Cool, concern withdrawn.

**Pull request merged**
