### PR TITLE
bug: Allow arbitrary args for options and head functions

### LINKED ISSUE #415: bug: Allow arbitrary arguments for endpoint options and head calls
These are no-op functions which currently fail because we've changed the number of valid arguments that could be passed in.

### PR DESCRIPTION
**Pull request by jrconlin**
closes #415

@bbangert r?

### CODE REVIEW

**Comment by jrconlin** [comment]
NOTE: pushing this one now to fix site brokenness. Going to write up proper integration test that exercises this aspect later, but short on time now.

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/issues/417

**Comment by bbangert** [comment]
Does this close 417 too? Little confused why you commented with just that.

**Comment by jrconlin** [comment]
Sorry, added a bit more context to the comment. I merely wanted to reference the outstanding issue in this patch.

**Comment by bbangert** [comment]
r+

**Pull request merged**
