### PR TITLE
cleanup ap_settings

### PR DESCRIPTION
**Pull request by pjenvey**
Some cleanup while I was in here -- more than I originally intended. I extracted into the new BaseHandler to make sure PyCharm was as happy as it can be. There's more that can go into it, but enough for now

r? @jrconlin @bbangert

### CODE REVIEW

**Comment by jrconlin** [comment]
looks good, r+

Wondering if we should merge this first, then rebase #637

**Comment by pjenvey** [comment]
this managed to avoid db/test_db so they should merge fine, I can rebase this easily enough anyway

**Comment by pjenvey** [comment]
Added a couple minor updates: fully moved _init_info into base and updated a couple docstrings

**Comment by bbangert** [comment]
r+

**Pull request merged**
