### PR TITLE
Remove unused ver from GCM data.

### PR DESCRIPTION
**Pull request by jrconlin**
So unused, there wasn't even a test to check for it.

@bbangert r?

### CODE REVIEW

**Comment by bbangert** [comment]
1.10.1 was already cut? Does this need to go out urgently for a .2?

**Comment by jrconlin** [comment]
Ah, changelog still had 1.10.1 marked as (**dev**)
will make 1.11

**Comment by bbangert** [comment]
It should be marked as the release, there's branch conflicts right now.

**Comment by jrconlin** [comment]
closing in favor of PR #327

**Pull request closed without merging**
