### PR TITLE
bug: add URI to error messages to aid in bad senderIDs

### PR DESCRIPTION
**Pull request by jrconlin**
Some bad senderids are cropping up, with values set to None. Add the uri
to the error log to determine if this is a bad URL or if there's some
other issue at play.

issue #630 

@bbangert @pjenvey r?

### CODE REVIEW

**Comment by pjenvey** [comment]
Might put want to pass uri along too?

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/pull/633/files#diff-2ec21160eb2bf471080e5ebaab11d4f3R718 passes the request URI to the registration endpoint as a keyword arg. 
https://github.com/mozilla-services/autopush/pull/633/files#diff-2754a4b01a815a790fbcdb94cfe2a08eR128 applies the kwarg provided URI to the logging message. 

Is that what you're looking for?

**Comment by pjenvey** [comment]
r+

**Comment by bbangert** [comment]
r+

**Comment by jrconlin** [comment]
#637 resolves and closes this issue.

**Pull request merged**
